INSERT INTO proportion(ID, PROPORTION) VALUES
  (1, 'Extra Small'),
  (2, 'Small'),
  (3, 'Medium'),
  (4, 'Large'),
  (5, 'Extra Large');

INSERT INTO state(ID, STATE) VALUES
    (1, 'Prestine'),
    (2, 'Excellent'),
    (3, 'Very Good'),
    (4, 'Good'),
    (5, 'Used'),
    (6, 'Poor');

INSERT INTO extras(ID, EXTRAS) VALUES
    (1, 'Box'),
    (2, 'Dustbag'),
    (3, 'Bag Charm'),
    (4, 'Authenticity Card'),
    (5, 'Pouch'),
    (6, 'Name Tag'),
    (7, 'Shoulder Strip'),
    (8, 'Padlock & Key'),
    (9, 'Mirror');

INSERT INTO brand (ID, BRAND) VALUES
    (1, 'Austria'),
    (2, 'Belgium'),
    (3, 'Bulgaria'),
    (4, 'Croatia'),
    (5, 'Cyprus'),
    (6, 'Czech Republic'),
    (7, 'Denmark'),
    (8, 'Estonia'),
    (9, 'Finland'),
    (10, 'France'),
    (11, 'Germany'),
    (12, 'Greece'),
    (13, 'Hungary'),
    (14, 'Iceland'),
    (15, 'Italy'),
    (16, 'Latvia'),
    (17, 'Liechtenstein'),
    (18, 'Lithuania'),
    (19, 'Luxembourg'),
    (20, 'Malta'),
    (21, 'Netherlands'),
    (22, 'Norway'),
    (23, 'Poland'),
    (24, 'Portugal'),
    (25, 'Slovakia'),
    (26, 'Slovenia'),
    (27, 'Spain'),
    (28, 'Sweden'),
    (29, 'United Kingdom');

INSERT INTO brand(ID, BRAND) VALUES
    (1, 'Alexander McQueen'),
    (2, 'Alexander Wang'),
    (3, 'Balenciaga'),
    (4, 'Bottega Veneta'),
    (5, 'Burberry'),
    (6, 'Bvlgari'),
    (7, 'Cartier'),
    (8, 'Celine'),
    (9, 'Chanel'),
    (10, 'Dior'),
    (11, 'Dolce&Gabbana'),
    (12, 'Fendi'),
    (13, 'Givenchy'),
    (14, 'Gucci'),
    (15, 'Hermes'),
    (16, 'Jacquemus'),
    (17, 'Loewe'),
    (18, 'Louis Vuitton'),
    (19, 'MCM'),
    (20, 'Miu Miu'),
    (21, 'Mulberry'),
    (22, 'Off White'),
    (23, 'Prada'),
    (24, 'Salvatore Ferragamo'),
    (25, 'Stella McCartney'),
    (26, 'The Row'),
    (27, 'Valentino'),
    (28, 'Versace'),
    (29, 'YSL');
